### ISSUE TITLE
nodeseek使用cookie签到失败

### ISSUE THREAD

**Issue by sk163** [kukume/tgbot#15]
#手动执行结果
NodeSeek签到失败，未获取到NodeSeek签到执行结果
查看了网站，确实没有签到成功。

日志报错如下：
```
#NodeSeek签到失败异常信息
未获取到NodeSeek签到执行结果
java.lang.IllegalStateException: 未获取到NodeSeek签到执行结果
 at me.kuku.telegram.logic.NodeSeekLogic.querySign(NodeSeekLogic.kt:23)
 at me.kuku.telegram.logic.NodeSeekLogic$querySign$1.invokeSuspend(NodeSeekLogic.kt)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
 at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by kukume** [comment]
签到的时候被cf 5s盾了。

**Comment by sk163** [comment]
> 签到的时候被cf 5s盾了。

呃…多谢…请问这个还有办法绕过么？

**Comment by kukume** [comment]
明天再看看，今天我已经签到过了，明天试试模拟点击，看看会不会跳盾出来。

**Comment by sk163** [comment]
> 明天再看看，今天我已经签到过了，明天试试模拟点击，看看会不会跳盾出来。

好嘞~😁

**Comment by kukume** [comment]
加了点请求头，疑似已修复。你可以试试手动执行。

**Comment by sk163** [comment]
> 加了点请求头，疑似已修复。你可以试试手动执行。

刚才更新执行后，可以返回查询结果了：
```
#手动执行结果
NodeSeek签到失败，今天已完成签到，请勿重复操作
```
等明天再签到提交时，再观察一下，多谢多谢~

**Comment by sk163** [comment]
已验证，没问题了👍🏻
