### ISSUE TITLE
阿里云盘领取失败

### ISSUE THREAD

**Issue by dudt** [kukume/tgbot#16]
![image](https://github.com/kukume/tgbot/assets/19968269/8ec52262-3ae1-4a99-96cf-be335dff3264)
都好久了。签到正常，但是不自动领取奖励

**Comment by dudt** [comment]
> /exec手动领取可以成功吗？

手动可以领取

**Comment by kukume** [comment]
尝试延后时间领取奖励。明天再看看能否成功

**Comment by dudt** [comment]
> 尝试延后时间领取奖励。明天再看看能否成功

还是不行哦
![image](https://github.com/kukume/tgbot/assets/19968269/fdd9bd30-80f6-4c37-8465-ac6f22ebdbbd)

**Comment by kukume** [comment]
我是成功的。 提供一下任务和错误日志

**Comment by dudt** [comment]
![image](https://github.com/kukume/tgbot/assets/19968269/e72d8a19-aaae-4165-a755-3c8a849b2604)
#阿里云盘签到失败异常信息
RewardGoodsFailed
java.lang.IllegalStateException: RewardGoodsFailed
 at me.kuku.telegram.logic.AliDriveLogic.receive$suspendImpl(AliDriveLogic.kt:231)
 at me.kuku.telegram.logic.AliDriveLogic$receive$1.invokeSuspend(AliDriveLogic.kt)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
 at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)



#阿里云盘领取当日任务奖励签到失败异常信息
RewardGoodsFailed-兑换失败
java.lang.IllegalStateException: RewardGoodsFailed-兑换失败
 at me.kuku.telegram.logic.AliDriveLogic.check(AliDriveLogic.kt:210)
 at me.kuku.telegram.logic.AliDriveLogic.receiveTask$suspendImpl(AliDriveLogic.kt:243)
 at me.kuku.telegram.logic.AliDriveLogic$receiveTask$1.invokeSuspend(AliDriveLogic.kt)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
 at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
 at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by kukume** [comment]
阿里云的任务名称。

**Comment by kukume** [comment]
我随机挑了一个领取失败的测试，发现签到接口返回的日期乱套了。并且普通的签到奖励也领取不了。
你尝试重新在机器人登陆阿里云盘，看是否能成功领取。
