### ISSUE TITLE
阿里云盘 nodeseek 失效

### ISSUE THREAD

**Issue by ssssssshi** [kukume/tgbot#22]
#自动签到失败提醒
阿里云盘执行失败，Forbidden

#自动签到失败提醒
阿里云盘时光设备间执行失败，Forbidden-请升级最新客户端访问

nodeseek登录的时候

com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/tmp/playwright-java-15511725094164063278/package/lib/server/progress.js:78:26)
    at Frame.waitForSelector (/tmp/playwright-java-15511725094164063278/package/lib/server/frames.js:619:23)
    at FrameDispatcher.waitForSelector (/tmp/playwright-java-15511725094164063278/package/lib/server/dispatchers/frameDispatcher.js:106:103)
    at FrameDispatcher._handleCommand (/tmp/playwright-java-15511725094164063278/package/lib/server/dispatchers/dispatcher.js:94:40)
    at DispatcherConnection.dispatch (/tmp/playwright-java-15511725094164063278/package/lib/server/dispatchers/dispatcher.js:361:39)
}
Call log:
- waiting for locator("#stacked-email") to be visible

**Comment by kukume** [comment]
阿里云盘的解决不了。不会逆向安卓.so
nodeseek暂时自己抓下包，抓所有cookie。

**Comment by ssssssshi** [comment]
好的 感谢
