### ISSUE TITLE
oracle cloud 管理添加完所有信息后查询及操作时报错

### ISSUE THREAD

**Issue by Nodewebzsz** [kukume/tgbot#26]
进行查询及操作时报错：

java.lang.IllegalArgumentException: Private key must be in PEM format

Private key内容添加的是api密钥.PEM文件的所有内容

**Comment by kukume** [comment]
是添加的这个吗？
![QQ_1720399998365](https://github.com/kukume/tgbot/assets/45278810/8c15b013-d86a-47e9-82f7-a709cacad786)
这个私钥文件的全部内容，
以`-----BEGIN PRIVATE KEY-----`开始的

**Comment by Nodewebzsz** [comment]
是的

**Comment by Nodewebzsz** [comment]
就在今天nodeseek的签到也出现异常

**Comment by kukume** [comment]
我刚刚添加了一次，正常。

**Comment by Nodewebzsz** [comment]
> 我刚刚添加了一次，正常。

我拉取了最新的镜像重新部署了，添加之后进行查询操作还是报错，java.lang.IllegalArgumentException: Private key must be in PEM format


nodeseek签到也还是有问题报错

**Comment by kukume** [comment]
已新增发送private key文件的方式。
你更新用这种方式试一下

**Comment by Nodewebzsz** [comment]
> 已新增发送private key文件的方式。 你更新用这种方式试一下

重新粘贴内容保存之后好像key重复报错了
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: com.mongodb.MongoWriteException: Write operation error on server mongo:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: tg.oci index: remark dup key: { remark: "圣何塞" }', details={}}.
        at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$createSingleWriteRequestMono$27(MongoOperationPublisher.java:475) ~[mongodb-driver-reactivestreams-5.0.1.jar!/:na]
        at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3840) ~[reactor-core-3.6.7.jar!/:3.6.7]
        at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3930) ~[reactor-core-3.6.7.jar!/:3.6.7]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.6.7.jar!/:3.6.7]
        ... 66 common frames omitted

**Comment by kukume** [comment]
备注重复了。
换个备注名字呗。或者删掉已存在的

**Comment by Nodewebzsz** [comment]
> 备注重复了。 换个备注名字呗。或者删掉已存在的

Request Endpoint: https://iaas.us-sanjose-1.oraclecloud.com/20160918/instances?compartmentId=************
Troubleshooting Tips: See https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_401__401_notauthenticated for more information about resolving this error
Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/ListInstances for details on this operation's requirements.
To get more info on the failing request, you can enable debug level logs as mentioned in `Using SLF4J for Logging section` in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm.
If you are unable to resolve this Compute issue, please contact Oracle support and provide them this full error message.
        at com.oracle.bmc.http.internal.ClientCall.lambda$checkError$18(ClientCall.java:820) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:144) ~[na:na]
        at com.oracle.bmc.http.internal.ClientCall.checkError(ClientCall.java:776) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at com.oracle.bmc.http.internal.ClientCall.transformResponse(ClientCall.java:641) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at com.oracle.bmc.http.internal.ClientCall.lambda$callAsyncImpl$24(ClientCall.java:1033) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[na:na]
        at com.oracle.bmc.http.internal.SyncFutureWaiter$Waiter.waitAndWork(SyncFutureWaiter.java:63) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at com.oracle.bmc.http.internal.SyncFutureWaiter.listenForResult(SyncFutureWaiter.java:32) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1101) ~[oci-java-sdk-common-3.44.1.jar!/:na]
        at com.oracle.bmc.core.ComputeClient.listInstances(ComputeClient.java:2811) ~[oci-java-sdk-core-3.44.1.jar!/:na]
        at me.kuku.telegram.logic.OciLogic.listInstances(OciLogic.kt:226) ~[!/:1.0-SNAPSHOT]
        at me.kuku.telegram.extension.OciExtension$operate$5.invokeSuspend(OciExtension.kt:263) ~[!/:1.0-SNAPSHOT]
        at me.kuku.telegram.extension.OciExtension$operate$5.invoke(OciExtension.kt) ~[!/:1.0-SNAPSHOT]
        at me.kuku.telegram.extension.OciExtension$operate$5.invoke(OciExtension.kt) ~[!/:1.0-SNAPSHOT]
        at me.kuku.telegram.context.TelegramSubscribe$invoke$2.invokeSuspend(TelegramSubscriber.kt:232) ~[!/:1.0-SNAPSHOT]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-2.0.0.jar!/:2.0.0-release-341]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.8.1.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.8.1.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811) ~[kotlinx-coroutines-core-jvm-1.8.1.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) ~[kotlinx-coroutines-core-jvm-1.8.1.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) ~[kotlinx-coroutines-core-jvm-1.8.1.jar!/:na]


删除了，我用已经被封的账户测试了下，日志报错了，但是点击oci的其他按钮“查看实例”等没有反应，最好给个前端报错提示
