### ISSUE TITLE
nodeseek签到报错

### ISSUE THREAD

**Issue by Nodewebzsz** [kukume/tgbot#28]
m.k.t.context.TelegramExceptionHandler   : Unexpected error occurred in telegram subscribe

io.ktor.client.network.sockets.SocketTimeoutException: Socket timeout has expired [url=https://api.jpa.cc/nodeseek/sign?cookie=sortBy%3DpostTime%3B+session%3D3881cd8160dff4a03da140d870e98c16%3B+smac%3D1720341630-UN_Q-gqh-BMXlXZg7oHqz1Jz6hrfF8VmG4Z3FAiuLeg%3B+hmti_%3D1720344938-rr_7KahLHAmxTijDuFFOBgG8RQgdwCqy60oBIVvF27ku%3B+colorscheme%3Ddark%3B+cf_clearance%3DutVFG9iEmhSI8YvTbxbX8NKOWFnwYSwauhKATLevxnc-1720577272-1.0.1.1-2zKoV9pb4xsVGupYe8bi7j41ipXXveq0h.kHZd3qtsLStfheErR2j6GoYNQeuaYLpXdZqNhAuVgTSlZaqsHWHg&random=true, socket_timeout=unknown] ms
        at io.ktor.client.plugins.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:239) ~[ktor-client-core-jvm-2.3.11.jar!/:2.3.11]
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:80) ~[ktor-client-okhttp-jvm-2.3.11.jar!/:2.3.11]
        at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1) ~[ktor-client-okhttp-jvm-2.3.11.jar!/:2.3.11]
        at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39) ~[ktor-client-okhttp-jvm-2.3.11.jar!/:2.3.11]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) ~[okhttp-4.12.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.12.0.jar!/:na]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.12.0.jar!/:na]
        ... 3 common frames omitted

**Comment by kukume** [comment]
服务器挂掉了。我稍后更新一下api的文docker镜像把。

**Comment by kukume** [comment]
更新了一下镜像，https://hub.docker.com/r/kukume/sk
然后在配置文件中填入你的api的url

**Comment by Nodewebzsz** [comment]
> 更新了一下镜像，https://hub.docker.com/r/kukume/sk 然后在配置文件中填入你的api的url

![image](https://github.com/kukume/tgbot/assets/23263051/16697750-2de9-4926-8427-b0331c0a1968)
是这里吗？

**Comment by kukume** [comment]
是的

**Comment by Nodewebzsz** [comment]
这个没问题了

**Comment by Nodewebzsz** [comment]
签到功能老是隔几天就自动解绑了登录状态，需要再次手动添加cookie

**Comment by kukume** [comment]
隔几天cookie失效还是什么意思？
我没有问题。

**Comment by Nodewebzsz** [comment]
> 隔几天cookie失效还是什么意思？ 我没有问题。

之前还没这个问题，我最近发现隔个两三天自动签到就失效了不知道啥原因，我看了下我是cookie登录的，然后进入机器人发现处于未登录状态，刚刚我重新设置有出现“java.lang.IllegalStateException: 访问api受限，请联系bot拥有者检查api服务器”不知道啥情况

**Comment by kukume** [comment]
是我的机器人还是自建的机器人，连不上api，如果没设置就是默认我建的api。
未登陆状态是/exec 进去提示未绑定nodeseek吗？

**Comment by kukume** [comment]
3个星期就发现cookie失效了一次，抓包的网页也退出了登录状态。
是没有问题的。
