### ISSUE TITLE
Hostloc 自动签到失败，密码或cookie登录报错

### ISSUE THREAD

**Issue by sk163** [kukume/tgbot#31]
#HostLoc签到失败异常信息
未知异常原因
java.lang.NullPointerException
 at me.kuku.telegram.logic.HostLocLogic.checkLogin(HostLocLogic.kt:37)
 at me.kuku.telegram.logic.HostLocLogic.access$checkLogin(HostLocLogic.kt:12)
 at me.kuku.telegram.logic.HostLocLogic$checkLogin$1.invokeSuspend(HostLocLogic.kt)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:200)
 at io.ktor.utils.io.internal.CancellableReusableContinuation.resumeWith(CancellableReusableContinuation.kt:93)
 at io.ktor.utils.io.ByteBufferChannel.resumeReadOp(ByteBufferChannel.kt:2104)
 at io.ktor.utils.io.ByteBufferChannel.tryTerminate$ktor_io(ByteBufferChannel.kt:390)
 at io.ktor.utils.io.ByteBufferChannel.close(ByteBufferChannel.kt:135)
 at io.ktor.utils.io.CoroutinesKt$launchChannel$1.invoke(Coroutines.kt:158)
 at io.ktor.utils.io.CoroutinesKt$launchChannel$1.invoke(Coroutines.kt:157)
 at kotlinx.coroutines.InternalCompletionHandler$UserSupplied.invoke(CompletionHandler.common.kt:67)
 at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)
 at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1502)
 at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:322)
 at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:239)
 at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:917)
 at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:874)
 at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:839)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:97)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
 at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

**Comment by kukume** [comment]
应该没问题了，目前2天都正常。

**Comment by sk163** [comment]
多谢👍
