### ISSUE TITLE
Nodeseek cookie 签到timeout

### ISSUE THREAD

**Issue by eddiehex** [kukume/tgbot#9]
```
2023-10-24T16:49:04.877+08:00 ERROR 1 --- [               ] m.k.t.utils.TelegramExceptionHandler     : Unexpected error occurred in telegram subscribe

io.ktor.client.network.sockets.SocketTimeoutException: Socket timeout has expired [url=https://api.jpa.cc/nodeseek/sign?cookie=session%xxxxxxxxxxxxxxxxxxxxx&random=true, socket_timeout=unknown] ms
	at io.ktor.client.plugins.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:239) ~[ktor-client-core-jvm-2.3.5.jar!/:2.3.5]
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:80) ~[ktor-client-okhttp-jvm-2.3.5.jar!/:2.3.5]
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1) ~[ktor-client-okhttp-jvm-2.3.5.jar!/:2.3.5]
	at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39) ~[ktor-client-okhttp-jvm-2.3.5.jar!/:2.3.5]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) ~[okhttp-4.11.0.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.net.SocketTimeoutException: timeout
```

**Comment by kukume** [comment]
应该签到成功了的。

eddiehex ***@***.***> 于 2023年10月24日周二 17:00写道：

**Comment by eddiehex** [comment]
不好意思，是成功的，只不过telegram 响应有点慢 😂
